/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#23191b',
        'surface-bright': '#fff8f9',
        'tertiary-container': '#fbe5e8',
        'surface-container': '#fbe8eb',
        'inverse-primary': '#ffb3c0',
        'surface-variant': '#f7dcdf',
        tertiary: '#735a5d',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#ffe4e8',
        'on-tertiary-container': '#301116',
        'on-primary-fixed': '#3f0012',
        'on-tertiary-fixed-variant': '#543e41',
        'error-container': '#ffdad6',
        'on-surface': '#201a1b',
        'on-primary-container': '#ffeef0',
        secondary: '#76565a',
        'primary-container': '#a30f37',
        'secondary-fixed': '#ffd9df',
        'inverse-surface': '#362f30',
        'primary-fixed-dim': '#ffb3c0',
        'surface-container-lowest': '#ffffff',
        background: '#fffcfc',
        'outline-variant': '#ecd3d6',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#800826',
        'secondary-fixed-dim': '#e4bdc3',
        'surface-container-highest': '#f5d6da',
        'surface-container-high': '#fae1e4',
        'surface-container-low': '#fef2f4',
        'on-background': '#201a1b',
        'inverse-on-surface': '#fceeed',
        'surface-dim': '#e6d0d3',
        outline: '#857375',
        'tertiary-fixed-dim': '#debcc0',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffd9df',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'on-secondary-container': '#2b1517',
        'on-secondary-fixed-variant': '#5c3f43',
        surface: '#fffcfc',
        'tertiary-fixed': '#ffd9df',
        primary: '#9b113e',
        'on-surface-variant': '#514345',
        'on-error': '#ffffff',
        'surface-tint': '#9b113e',
        'on-tertiary-fixed': '#281518',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '1rem',
        gutter: '1.5rem',
        xl: '2rem',
        'sidebar-width': '260px',
        xs: '0.25rem',
        base: '4px',
        sm: '0.5rem',
        lg: '1.5rem',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
}
