/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#121c28',
        'surface-bright': '#f8f9ff',
        'tertiary-container': '#676e79',
        'surface-container': '#e6eeff',
        'inverse-primary': '#b4c5ff',
        'surface-variant': '#d9e3f6',
        tertiary: '#4f5660',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#dbe1ff',
        'on-tertiary-container': '#ebf1fe',
        'on-primary-fixed': '#00174b',
        'on-tertiary-fixed-variant': '#404752',
        'error-container': '#ffdad6',
        'on-surface': '#121c2a',
        'on-primary-container': '#eeefff',
        secondary: '#555f6d',
        'primary-container': '#2563eb',
        'secondary-fixed': '#d9e3f4',
        'inverse-surface': '#27313f',
        'primary-fixed-dim': '#b4c5ff',
        'surface-container-lowest': '#ffffff',
        background: '#f8f9ff',
        'outline-variant': '#c3c6d7',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-fixed-dim': '#bdc7d8',
        'surface-container-highest': '#d9e3f6',
        'surface-container-high': '#dee9fc',
        'surface-container-low': '#eff4ff',
        'on-background': '#121c2a',
        'inverse-on-surface': '#eaf1ff',
        'surface-dim': '#d0dbed',
        outline: '#737686',
        'tertiary-fixed-dim': '#c0c7d3',
        'on-secondary': '#ffffff',
        'secondary-container': '#d6e0f1',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'on-secondary-container': '#596372',
        'on-secondary-fixed-variant': '#3e4755',
        surface: '#f8f9ff',
        'tertiary-fixed': '#dce3f0',
        primary: '#004ac6',
        'on-surface-variant': '#434655',
        'on-error': '#ffffff',
        'surface-tint': '#0053db',
        'on-tertiary-fixed': '#151c25',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '1rem',
        gutter: '1.5rem',
        xl: '2rem',
        'sidebar-width': '260px',
        xs: '0.25rem',
        base: '4px',
        sm: '0.5rem',
        lg: '1.5rem',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
}
